Torus.ext.abusefilter.rebuild = function() {
	var tabs = ['filter', 'examine', 'help'];
	var frag = document.createDocumentFragment();
		for(var i = 0; i < tabs.length; i++) {
			var li = document.createElement('li');
				li.className = 'torus-sidebar-button';
				if(i == Torus.ext.options.selected) {li.classList.add('torus-sidebar-button-selected');}
				li.setAttribute('data-id', tabs[i]);
				li.textContent = Torus.i18n.text('ext-abusefilter-sidebar-' + tabs[i]);
				li.addEventListener('click', Torus.ext.abusefilter.click_sidebar);
			frag.appendChild(li);
		}
	Torus.ext.abusefilter.ui.sidebar = frag;

	var frag = document.createDocumentFragment();
		var fieldset = document.createElement('fieldset');
			fieldset.id = 'torus-ext-abusefilter-text';
			Torus.ui.ids['ext-abusefilter-text'] = fieldset;
			var legend = document.createElement('legend');
				legend.textContent = Torus.i18n.text('ext-abusefilter-text');
			fieldset.appendChild(legend);
			var textarea = document.createElement('textarea');
				textarea.id = 'torus-ext-abusefilter-input';
				Torus.ui.ids['ext-abusefilter-input'] = textarea;
				textarea.value = Torus.ext.abusefilter.filter_text;
				textarea.addEventListener('blur', Torus.ext.abusefilter.blur_input);
			fieldset.appendChild(textarea);
			var pre = document.createElement('pre');
				pre.id = 'torus-ext-abusefilter-error';
				Torus.ui.ids['ext-abusefilter-error'] = pre;
				pre.classList.add('torus-hide');
			fieldset.appendChild(pre);
		frag.appendChild(fieldset);
		var fieldset = document.createElement('fieldset');
			fieldset.id = 'torus-ext-abusefilter-actions';
			Torus.ui.ids['ext-abusefilter-actions'] = fieldset;
			var legend = document.createElement('legend');
				legend.textContent = Torus.i18n.text('ext-abusefilter-actions');
			fieldset.appendChild(legend);
			var div = document.createElement('div');
				var input = document.createElement('input');
					input.id = 'torus-ext-abusefilter-enabled-enabled';
					Torus.ui.ids['ext-abusefilter-enabled-enabled'] = input;
					input.type = 'checkbox';
					input.checked = Torus.ext.abusefilter.params.enabled.enabled;
					input.setAttribute('data-action', 'enabled');
					input.setAttribute('data-param', 'enabled');
					input.addEventListener('click', Torus.ext.abusefilter.update_action);
				div.appendChild(input);
				div.appendChild(document.createTextNode(' '));
				var label = document.createElement('label');
					label.textContent = Torus.i18n.text('ext-abusefilter-label-enabled');
					label.setAttribute('for', 'torus-ext-abusefilter-enabled-enabled');
				div.appendChild(label);
			fieldset.appendChild(div);
			var div = document.createElement('div');
				var input = document.createElement('input');
					input.id = 'torus-ext-abusefilter-ping-enabled';
					Torus.ui.ids['ext-abusefilter-ping-enabled'] = input;
					input.type = 'checkbox';
					input.checked = Torus.ext.abusefilter.params.ping.enabled;
					input.setAttribute('data-action', 'ping');
					input.setAttribute('data-param', 'enabled');
					input.addEventListener('click', Torus.ext.abusefilter.update_action);
				div.appendChild(input);
				div.appendChild(document.createTextNode(' '));
				var label = document.createElement('label');
					label.textContent = Torus.i18n.text('ext-abusefilter-label-ping');
					label.setAttribute('for', 'torus-ext-abusefilter-ping-enabled');
				div.appendChild(label);
			fieldset.appendChild(div);
			var div = document.createElement('div');
				var input = document.createElement('input');
					input.id = 'torus-ext-abusefilter-warn-enabled';
					Torus.ui.ids['ext-abusefilter-warn-enabled'] = input;
					input.type = 'checkbox';
					input.checked = Torus.ext.abusefilter.params.warn.enabled;
					input.setAttribute('data-action', 'warn');
					input.setAttribute('data-param', 'enabled');
					input.addEventListener('click', Torus.ext.abusefilter.update_action);
				div.appendChild(input);
				div.appendChild(document.createTextNode(' '));
				var label = document.createElement('label');
					label.textContent = Torus.i18n.text('ext-abusefilter-label-warn');
					label.setAttribute('for', 'torus-ext-abusefilter-warn-enabled');
				div.appendChild(label);
				var params = document.createElement('div');
					params.id = 'torus-ext-abusefilter-warn-params';
					Torus.ui.ids['ext-abusefilter-warn-params'] = params;
					params.classList.add('torus-hide');
					params.classList.add('torus-ext-abusefilter-params');
					var label = document.createElement('label');
						label.textContent = Torus.i18n.text('ext-abusefilter-label-warn-message');
						label.setAttribute('for', 'torus-ext-abusefilter-warn-message');
					params.appendChild(label);
					var input = document.createElement('input');
						input.id = 'torus-ext-abusefilter-warn-message';
						Torus.ui.ids['ext-abusefilter-warn-message'] = input;
						input.type = 'text';
						input.value = Torus.ext.abusefilter.params.warn.message;
						input.setAttribute('data-action', 'warn');
						input.setAttribute('data-param', 'message');
						input.addEventListener('blur', Torus.ext.abusefilter.update_action);
					params.appendChild(input);
				div.appendChild(params);
			fieldset.appendChild(div);
			var div = document.createElement('div');
				var input = document.createElement('input');
					input.id = 'torus-ext-abusefilter-kick-enabled';
					Torus.ui.ids['ext-abusefilter-kick-enabled'] = input;
					input.type = 'checkbox';
					input.checked = Torus.ext.abusefilter.params.kick.enabled;
					input.setAttribute('data-action', 'kick');
					input.setAttribute('data-param', 'enabled');
					input.addEventListener('click', Torus.ext.abusefilter.update_action);
				div.appendChild(input);
				div.appendChild(document.createTextNode(' '));
				var label = document.createElement('label');
					label.textContent = Torus.i18n.text('ext-abusefilter-label-kick');
					label.setAttribute('for', 'torus-ext-abusefilter-kick-enabled');
				div.appendChild(label);
			fieldset.appendChild(div);
			var div = document.createElement('div');
				var input = document.createElement('input');
					input.id = 'torus-ext-abusefilter-ban-enabled';
					Torus.ui.ids['ext-abusefilter-ban-enabled'] = input;
					input.type = 'checkbox';
					input.checked = Torus.ext.abusefilter.params.ban.enabled;
					input.setAttribute('data-action', 'ban');
					input.setAttribute('data-param', 'enabled');
					input.addEventListener('click', Torus.ext.abusefilter.update_action);
				div.appendChild(input);
				div.appendChild(document.createTextNode(' '));
				var label = document.createElement('label');
					label.textContent = Torus.i18n.text('ext-abusefilter-label-ban');
					label.setAttribute('for', 'torus-ext-abusefilter-ban-enabled');
				div.appendChild(label);
				var params = document.createElement('div');
					params.id = 'torus-ext-abusefilter-ban-params';
					Torus.ui.ids['ext-abusefilter-ban-params'] = params;
					params.classList.add('torus-hide');
					params.classList.add('torus-ext-abusefilter-params');
					var div2 = document.createElement('div');
						var label = document.createElement('label');
							label.textContent = Torus.i18n.text('ext-abusefilter-label-ban-expiry');
							label.setAttribute('for', 'torus-ext-abusefilter-ban-expiry');
						div2.appendChild(label);
						var input = document.createElement('input');
							input.id = 'torus-ext-abusefilter-ban-expiry';
							Torus.ui.ids['ext-abusefilter-ban-expiry'] = input;
							input.type = 'text';
							input.value = Torus.ext.abusefilter.params.ban.expiry;
							input.setAttribute('data-action', 'ban');
							input.setAttribute('data-param', 'expiry');
							input.addEventListener('blur', Torus.ext.abusefilter.update_action);
						div2.appendChild(input);
					params.appendChild(div2);
					var div2 = document.createElement('div');
						var label = document.createElement('label');
							label.textContent = Torus.i18n.text('ext-abusefilter-label-ban-summary');
							label.setAttribute('for', 'torus-ext-abusefilter-ban-summary');
						div2.appendChild(label);
						var input = document.createElement('input');
							input.id = 'torus-ext-abusefilter-ban-summary';
							Torus.ui.ids['ext-abusefilter-ban-summary'] = input;
							input.type = 'text';
							input.value = Torus.ext.abusefilter.params.ban.summary;
							input.setAttribute('data-action', 'ban');
							input.setAttribute('data-param', 'summary');
							input.addEventListener('blur', Torus.ext.abusefilter.update_action);
						div2.appendChild(input);
					params.appendChild(div2);
				div.appendChild(params);
			fieldset.appendChild(div);
			var div = document.createElement('div');
				var input = document.createElement('input');
					input.id = 'torus-ext-abusefilter-block-enabled';
					Torus.ui.ids['ext-abusefilter-block-enabled'] = input;
					input.type = 'checkbox';
					input.checked = Torus.ext.abusefilter.params.block.enabled;
					input.setAttribute('data-action', 'block');
					input.setAttribute('data-param', 'enabled');
					input.addEventListener('click', Torus.ext.abusefilter.update_action);
				div.appendChild(input);
				div.appendChild(document.createTextNode(' '));
				var label = document.createElement('label');
					label.textContent = Torus.i18n.text('ext-abusefilter-label-block');
					label.setAttribute('for', 'torus-ext-abusefilter-block-enabled');
				div.appendChild(label);
				var params = document.createElement('div');
					params.id = 'torus-ext-abusefilter-block-params';
					Torus.ui.ids['ext-abusefilter-block-params'] = params;
					params.classList.add('torus-hide');
					params.classList.add('torus-ext-abusefilter-params');
					var div2 = document.createElement('div');
						var label = document.createElement('label');
							label.textContent = Torus.i18n.text('ext-abusefilter-label-block-expiry');
							label.setAttribute('for', 'torus-ext-abusefilter-block-expiry');
						div2.appendChild(label);
						var input = document.createElement('input');
							input.id = 'torus-ext-abusefilter-block-expiry';
							Torus.ui.ids['ext-abusefilter-block-expiry'] = input;
							input.type = 'text';
							input.value = Torus.ext.abusefilter.params.block.expiry;
							input.setAttribute('data-action', 'block');
							input.setAttribute('data-param', 'expiry');
							input.addEventListener('blur', Torus.ext.abusefilter.update_action);
						div2.appendChild(input);
					params.appendChild(div2);
					var div2 = document.createElement('div');
						var label = document.createElement('label');
							label.textContent = Torus.i18n.text('ext-abusefilter-label-block-reason');
							label.setAttribute('for', 'torus-ext-abusefilter-block-reason');
						div2.appendChild(label);
						var input = document.createElement('input');
							input.id = 'torus-ext-abusefilter-block-reason';
							Torus.ui.ids['ext-abusefilter-block-reason'] = input;
							input.type = 'text';
							input.value = Torus.ext.abusefilter.params.block.reason;
							input.setAttribute('data-action', 'block');
							input.setAttribute('data-param', 'reason');
							input.addEventListener('blur', Torus.ext.abusefilter.update_action);
						div2.appendChild(input);
					params.appendChild(div2);
					var div2 = document.createElement('div');
						var input = document.createElement('input');
							input.id = 'torus-ext-abusefilter-block-autoblock';
							Torus.ui.ids['ext-abusefilter-block-autoblock'] = input;
							input.type = 'checkbox';
							input.checked = Torus.ext.abusefilter.params.block.autoblock;
							input.setAttribute('data-action', 'block');
							input.setAttribute('data-param', 'autoblock');
							input.addEventListener('click', Torus.ext.abusefilter.update_action);
						div2.appendChild(input);
						var label = document.createElement('label');
							label.textContent = Torus.i18n.text('ext-abusefilter-label-block-autoblock');
							label.setAttribute('for', 'torus-ext-abusefilter-block-autoblock');
						div2.appendChild(label);
					params.appendChild(div2);
					var div2 = document.createElement('div');
						var input = document.createElement('input');
							input.id = 'torus-ext-abusefilter-block-noemail';
							Torus.ui.ids['ext-abusefilter-block-noemail'] = input;
							input.type = 'checkbox';
							input.checked = Torus.ext.abusefilter.params.block.noemail;
							input.setAttribute('data-action', 'block');
							input.setAttribute('data-param', 'noemail');
							input.addEventListener('click', Torus.ext.abusefilter.update_action);
						div2.appendChild(input);
						var label = document.createElement('label');
							label.textContent = Torus.i18n.text('ext-abusefilter-label-block-noemail');
							label.setAttribute('for', 'torus-ext-abusefilter-block-noemail');
						div2.appendChild(label);
					params.appendChild(div2);
					var div2 = document.createElement('div');
						var input = document.createElement('input');
							input.id = 'torus-ext-abusefilter-block-allowusertalk';
							Torus.ui.ids['ext-abusefilter-block-allowusertalk'] = input;
							input.type = 'checkbox';
							input.checked = Torus.ext.abusefilter.params.block.allowusertalk;
							input.setAttribute('data-action', 'block');
							input.setAttribute('data-param', 'allowusertalk');
							input.addEventListener('click', Torus.ext.abusefilter.update_action);
						div2.appendChild(input);
						var label = document.createElement('label');
							label.textContent = Torus.i18n.text('ext-abusefilter-label-block-allowusertalk');
							label.setAttribute('for', 'torus-ext-abusefilter-block-allowusertalk');
						div2.appendChild(label);
					params.appendChild(div2);
					var div2 = document.createElement('div');
						var input = document.createElement('input');
							input.id = 'torus-ext-abusefilter-block-nocreate';
							Torus.ui.ids['ext-abusefilter-block-nocreate'] = input;
							input.type = 'checkbox';
							input.checked = Torus.ext.abusefilter.params.block.nocreate;
							input.setAttribute('data-action', 'block');
							input.setAttribute('data-param', 'nocreate');
							input.addEventListener('click', Torus.ext.abusefilter.update_action);
						div2.appendChild(input);
						var label = document.createElement('label');
							label.textContent = Torus.i18n.text('ext-abusefilter-label-block-nocreate');
							label.setAttribute('for', 'torus-ext-abusefilter-block-nocreate');
						div2.appendChild(label);
					params.appendChild(div2);
				div.appendChild(params);
			fieldset.appendChild(div);
		frag.appendChild(fieldset);
	Torus.ext.abusefilter.ui.filter = frag;

	var frag = document.createDocumentFragment();
		var div = document.createElement('div');
			var label = document.createElement('label');
				label.textContent = Torus.i18n.text('ext-abusefilter-label-examine');
				label.setAttribute('for', 'torus-ext-abusefilter-examine');
			div.appendChild(label);
			var input = document.createElement('input');
				input.id = 'torus-ext-abusefilter-examine';
				Torus.ui.ids['ext-abusefilter-examine'] = input;
				input.type = 'text';
				input.value = Torus.ext.abusefilter.examine;
				input.addEventListener('blur', Torus.ext.abusefilter.blur_examine);
			div.appendChild(input);
		frag.appendChild(div);
		var table = document.createElement('table');
		table.classList.add('wikitable');
		var tbody = document.createElement('tbody');
			var tr = document.createElement('tr');
				var th = document.createElement('th');
					th.textContent = Torus.i18n.text('ext-abusefilter-table-name');
				tr.appendChild(th);
				var th = document.createElement('th');
					th.textContent = Torus.i18n.text('ext-abusefilter-table-type');
				tr.appendChild(th);
				var th = document.createElement('th');
					th.textContent = Torus.i18n.text('ext-abusefilter-table-description');
				tr.appendChild(th);
			tbody.appendChild(tr);
			var vars = Torus.classes.AFEvaluator.default_vars;
			for(var i in vars) {
				if(typeof(vars[i]) == 'function') {continue;}
				var tr = document.createElement('tr');
					var td = document.createElement('td');
						var code = document.createElement('code');
							code.textContent = i;
						td.appendChild(code);
					tr.appendChild(td);
					var td = document.createElement('td');
						td.textContent = typeof(vars[i]);
					tr.appendChild(td);
					var td = document.createElement('td');
						td.id = 'torus-ext-abusefilter-examine-' + i;
						Torus.ui.ids['ext-abusefilter-examine-' + i] = td;
						td.textContent = '';
					tr.appendChild(td);
				tbody.appendChild(tr);
			}
		table.appendChild(tbody);
		frag.appendChild(table);
	Torus.ext.abusefilter.ui.examine = frag;

	var frag = document.createDocumentFragment();
		var h2 = document.createElement('h2');
			h2.textContent = Torus.i18n.text('ext-abusefilter-table-variables');
		frag.appendChild(h2);
		var table = document.createElement('table');
		table.classList.add('wikitable');
		var tbody = document.createElement('tbody');
			var tr = document.createElement('tr');
				var th = document.createElement('th');
					th.textContent = Torus.i18n.text('ext-abusefilter-table-name');
				tr.appendChild(th);
				var th = document.createElement('th');
					th.textContent = Torus.i18n.text('ext-abusefilter-table-type');
				tr.appendChild(th);
				var th = document.createElement('th');
					th.textContent = Torus.i18n.text('ext-abusefilter-table-description');
				tr.appendChild(th);
			tbody.appendChild(tr);
			var vars = Torus.classes.AFEvaluator.default_vars;
			for(var i in vars) {
				if(typeof(vars[i]) == 'function') {continue;}
				var tr = document.createElement('tr');
					var td = document.createElement('td');
						var code = document.createElement('code');
							code.textContent = i;
						td.appendChild(code);
					tr.appendChild(td);
					var td = document.createElement('td');
						td.textContent = typeof(vars[i]);
					tr.appendChild(td);
					var td = document.createElement('td');
						td.textContent = Torus.i18n.text('ext-abusefilter-help-' + i);
					tr.appendChild(td);
				tbody.appendChild(tr);
			}
		table.appendChild(tbody);
		frag.appendChild(table);
		var h2 = document.createElement('h2');
			h2.textContent = Torus.i18n.text('ext-abusefilter-table-functions');
		frag.appendChild(h2);
		var table = document.createElement('table');
		table.classList.add('wikitable');
		var tbody = document.createElement('tbody');
			var tr = document.createElement('tr');
				var th = document.createElement('th');
					th.textContent = Torus.i18n.text('ext-abusefilter-table-name');
				tr.appendChild(th);
				var th = document.createElement('th');
					th.textContent = Torus.i18n.text('ext-abusefilter-table-description');
				tr.appendChild(th);
			tbody.appendChild(tr);
			var vars = Torus.classes.AFEvaluator.default_vars;
			for(var i in vars) {
				if(typeof(vars[i]) != 'function') {continue;}
				var tr = document.createElement('tr');
					var td = document.createElement('td');
						var code = document.createElement('code');
							code.textContent = i;
						td.appendChild(code);
					tr.appendChild(td);
					var td = document.createElement('td');
						td.textContent = Torus.i18n.text('ext-abusefilter-help-' + i);
					tr.appendChild(td);
				tbody.appendChild(tr);
			}
		table.appendChild(tbody);
		frag.appendChild(table);
	Torus.ext.abusefilter.ui.help = frag;
}

Torus.ext.abusefilter.render = function(group) {
	if(!group || typeof group == 'object') {group = Torus.ext.abusefilter.selected;} //group == object when ui.activate fires

	if(Torus.ui.ids['window'].firstChild) { //an abusefilter group is already rendered, put it back
		Torus.ext.abusefilter.ui[Torus.ext.abusefilter.selected] = Torus.util.empty(Torus.ui.ids['window']);
	}

	for(var i = 0; i < Torus.ui.ids['sidebar'].children.length; i++) {
		if(Torus.ui.ids['sidebar'].children[i].getAttribute('data-id') == group) {Torus.ui.ids['sidebar'].children[i].classList.add('torus-sidebar-button-selected');}
		else {Torus.ui.ids['sidebar'].children[i].classList.remove('torus-sidebar-button-selected');}
	}

	Torus.ui.ids['window'].appendChild(Torus.ext.abusefilter.ui[group]);
	Torus.ui.ids['sidebar'].appendChild(Torus.ext.abusefilter.ui.sidebar);

	Torus.ext.abusefilter.selected = group;
}

Torus.ext.abusefilter.unrender = function(event) {
	Torus.ext.abusefilter.ui.sidebar = event.old_sidebar;
	Torus.ext.abusefilter.ui[Torus.ext.abusefilter.selected] = event.old_window;
}
